#!/usr/bin/env expect -d

# disables script output
log_user 0

proc exit_session {} {
  sleep .5
  send "exit"
  close
}

spawn tmux -f $env(TMUXCONF)

# Waiting for tmux to launch and attach
sleep 1

expect {
  "origin/master" {
    exit_session
    exit 0
  }
}
exit_session
exit 1
